apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  spec:
  ports:
  - port: 3306
  selector:
    app: sergiosanchezruiz-db
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: sergiosanchezruiz-db
  template:
    metadata:
      labels:
        app: sergiosanchezruiz-db
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pass
        - name: MYSQL_DATABASE
          value: test
        ports:
        - containerPort: 3306
          name: db-port
        volumeMounts:
        - name: db-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: db-persistent-storage
        persistentVolumeClaim:
          claimName: db-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
