apiVersion: apps/v1
kind: Deployment
metadata:
  name: sergiosanchezruiz-webanuncios-prc
spec:
  selector:
    matchLabels:
      app: sergiosanchezruiz-webanuncios-prc
  template:
    metadata:
      labels:
        app: sergiosanchezruiz-webanuncios-prc
    spec:
      containers:
      - name: java
        image: codeurjc/java-webapp-bbdd:v2
        ports:
          - containerPort: 8080
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pass
        - name: MYSQL_DATABASE
          value: test
---
apiVersion: v1
kind: Service
metadata:
  name: sergiosanchezruiz-webanuncios-service-prc
  labels:
    app: sergiosanchezruiz-webanuncios-prc
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: sergiosanchezruiz-webanuncios-port
  selector:
    app: sergiosanchezruiz-webanuncios-prc
  type: ClusterIP
